### ISSUE TITLE
Writing an array fails?

### ISSUE THREAD

**Issue by kevzettler** [maxogden/csv-write-stream#40]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer
    at validChunk (_stream_writable.js:257:10)
    at WriteStream.Writable.write (_stream_writable.js:292:21)
```

```js
import csvWrite from 'csv-write-stream';
const successStream = csvWrite({
  sendHeaders: false
}).pipe(
  fs.createWriteStream('success_intercom_updates.csv')
);
successStream.write([098098, 08907098, 070980]);
```

**Comment by notslang** [comment]
You should be able to write an array. This works for me:

```js
const csvWrite = require('csv-write-stream')
const fs = require('fs')

const successStream = csvWrite({
  sendHeaders: false,
  headers: ['one', 'two', 'three']
})
successStream.pipe(
  fs.createWriteStream('success_intercom_updates.csv')
)
successStream.write([98098, 8907098, 70980])
```

Chaining `pipe` to the end of `csvWrite(...)` doesn't work because `.pipe(...)` doesn't return the `csvWriteStream`. It returns the file write stream for `success_intercom_updates.csv` and _that_ only accepts a string or buffer.

...but I'm not sure why I get "Error: no headers specified" when I don't give headers with `sendHeaders: false`.
